DROP TABLE IF EXISTS business_partners CASCADE;

DROP TABLE IF EXISTS divisions CASCADE;

DROP TABLE IF EXISTS super_categories CASCADE;

DROP TABLE IF EXISTS categories CASCADE;

DROP TABLE IF EXISTS item_types CASCADE;

DROP TABLE IF EXISTS brands CASCADE;

DROP TABLE IF EXISTS brand_item_types CASCADE;

DROP TABLE IF EXISTS models CASCADE;

DROP TABLE IF EXISTS items CASCADE;

DROP TABLE IF EXISTS catalog_items CASCADE;

DROP TABLE IF EXISTS customers CASCADE;

DROP TABLE IF EXISTS customer_carts CASCADE;

DROP TABLE IF EXISTS customer_cart_items CASCADE;

COMMIT;